import streamlit as st
import pandas as pd
from groq import Groq,RateLimitError,APIConnectionError, APIStatusError
class MyChatBot:
    def __init__(self,name,max_tokens,model):
        self.name= name
        st.title(name)
        st.header(name)
        st.write("Note: the text generated by the chatbot is limited to 100 words due to some hardware and other constraints")
        self.chat_input = st.text_area("Ask Anything")
        self.chat_submit_btn = st.button("Submit")
        self.client = Groq(
    api_key=st.secrets["GROQ_API_KEY"],
        )
        self.messages = []
        self.max_tokens=max_tokens
        self.model = model
    def generate_text(self,question):
        self.messages.append({
                "role": "user",
                "content": question,
        });
        chat_completion = self.client.chat.completions.create(
        messages=[
            self.messages[-1]
        ],
        model=self.model,
        max_tokens=self.max_tokens,
    )
        response = chat_completion.choices[0].message.content
        self.messages.append({
                "role": "bot",
                "content": response,
        })
        return self.messages[-1]["content"]
    def run(self):
        if self.chat_submit_btn and self.chat_input != "":
            self.generate_text(self.chat_input)
        for i in self.messages:
            st.write(i["role"]+" === "+i["content"])
            
    

def main():
    try:
        bot = MyChatBot("Groq Streamlit ChatBot",
                    150,
                    "llama-3.3-70b-versatile")
        bot.run()
    except RateLimitError as rle:
        st.write("Got "+str(rle))
    except APIConnectionError as ace:
        st.write("Got "+str(ace))
    except APIStatusError as ase:
        st.write("Got "+str(ase))
    finally:
        st.write("That's All!")
if __name__=="__main__":
    main()
    

#st.write(pd.DataFrame({"A": [1,2,3],"B":[4,5,6]}))
