import streamlit as st
from groq import Groq,RateLimitError,APIConnectionError, APIStatusError
class MyChatBot:
    def __init__(self,name,max_tokens,model):
        self.name= name
        st.title(name)
        st.header(name)
        st.write("Note: the text generated by the chatbot is limited to 100 words due to some hardware and other constraints")
        self.chat_input = st.text_area("Ask Anything")
        self.chat_submit_btn = st.button("Submit")
        self.client = Groq(
    api_key=st.secrets["GROQ_API_KEY"],
        )
        if "history" not in st.session_state:
            st.session_state["history"] = []
        self.messages = st.session_state["history"]
        self.max_tokens=max_tokens
        self.model = model
    def generate_text(self,question):
        self.messages.append({
        "role": "user",
        "content": question,
        })
        try:
            chat_completion = self.client.chat.completions.create(
            messages=self.messages,
            model=self.model,
            max_tokens=self.max_tokens,
        )
        except (RateLimitError, APIConnectionError, APIStatusError) as e:
            self.messages.pop()
            st.error(f"Something went wrong: {e}")
            return  # stop here — no value needed, just exit before the crash below

        response = chat_completion.choices[0].message.content
        self.messages.append({
        "role": "assistant",
        "content": response,
    })
    def run(self):
        if self.chat_submit_btn and self.chat_input != "":
            self.generate_text(self.chat_input)
        for i in self.messages:
            st.chat_message(i["role"]).write(i["content"])
            
    

def main():
    try:
        bot = MyChatBot("Groq Streamlit ChatBot",
                    150,
                    "llama-3.3-70b-versatile")
        bot.run()
    except BaseException as e:
        st.write("Got "+str(e))
    finally:
        st.write("That's All!")
if __name__=="__main__":
    main()
